version: 0.2

phases:
  install:
    commands:
      - echo "***** Pushing website source to S3 *****"
  build:
    commands:
      - aws s3 sync --acl public-read ./ s3://${bucket_name}
      - aws s3 cp $CODEBUILD_SRC_DIR_list/public_suffix_list.dat s3://webops-publicsuffix/list/effective_tld_names.dat --acl public-read --content-type 'text/plain; charset=UTF-8'
      - aws s3 cp $CODEBUILD_SRC_DIR_list/public_suffix_list.dat s3://webops-publicsuffix/list/public_suffix_list.dat --acl public-read --content-type 'text/plain; charset=UTF-8'
